# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7063aae7a992b4f13a427b7dd3854dc726881c4880a27122959b52db94e22e55ba7bc91f1099e84d76b2f9898e1ea3cc4830b14c9827869bc5998814a1ef221d

test:
  secret_key_base: 4ebcc39e131793f366c588a561f9c278755d8e5b14ca7e47041ede964c697e31490270299cb2c6866bfe77de2c7f1083f5e3cf3abb0b24a6149785732f5fd868

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
